<?php

$abreviatura = "abreviatura";
$Abreviatura = "Abreviatura";
$Abrir = "Abrir";
$Acceso = "Acceso";
$Acciones = "Acciones";
$Activa = "Activa";
$Activar = "Activar";
$Activo = "Activo";
$Activos = "Activos";
$Actuacion = "Actuaci&oacute;n";
$Actuaciones = "Actuaciones";
$Actual = "Actual";
$actualizado = "actualizado";
$Actualizar = "Actualizar";
$Adjuntar = "Adjuntar";
$Adjuntos = "Adjuntos";
$Admin = "Admin.";
$Administracion = "Administraci&oacute;n";
$Administrador = "Administrador";
$Administrar = "Administrar";
$Administrativo = "Administrativo";
$a_efecto = "a efecto";
$AGENDA = "AGENDA";
$Agenda = "Agenda";
$Agendas = "Agendas";
$agendas = "agendas";
$Agrupacion = "Agrupaci&oacute;n";
$Alerta = "Alerta";
$Alertas = "Alertas";
$Alias = "Alias";
$Almacen = "Almac&eacute;n";
$Almacenes = "Almacenes";
$Alto = "Alto";
$Ambito = "&Aacute;mbito";
$Ambito_geografico = "&Aacute;mbito Geogr&aacute;fico";
$Anadir = "A&ntilde;adir";
$Anadir_Contacto = "A&ntilde;adir Contacto";
$Anadir_version = "A&ntilde;adir a Control Versi&oacute;n";
$AnadiryEliminarIncompatibles = "A&ntilde;adir y Eliminar Incompatibles";
$Ancho = "Ancho";
$Ano = "A&ntilde;o";
$Anos = "A&ntilde;os";
$Anotacion = "Anotaci&oacute;n";
$Antecedentes = "Antecedentes";
$Anterior = "Anterior";
$antiguo = "antiguo";
$Antiguo = "Antiguo";
$Anual = "Anual";
$Apellido = "Apellido";
$Aplicacion = "Aplicaci&oacute;n";
$Aplicaciones = "Aplicaciones";
$Aprobado = "Aprobado";
$Aprobar = "Aprobar";
$Area = "Area";
$Archivo = "Archivo";
$Archivos = "Archivos";
$Archivos_subidos = "Archivos subidos";
$Articulos = "Articulos";
$Articulo = "Art&iacute;culo";
$articulo = "art&iacute;culo";
$Asociadas = "Asociadas";
$Asunto = "Asunto";
$Atencion = "Atenci&oacute;n";
$Atributo = "Atributo";
$Atributos = "Atributos";
$Auditoria = "Auditoria";
$AutoEmail = "AutoEmail";
$Autor = "Autor";
$Auxiliares = "Auxiliares";
$Aviso = "Aviso";
$Ayer = "Ayer";
$Ayuda = "Ayuda";

$Bancaria = "Bancaria";
$Base = "Base";
$Bases = "Bases";
$Bases_Datos = "Bases de Datos";
$Barras = "Barras";
$Base_imponible = "Base Imponible";
$Bienvenido = "Bienvenido";
$Billetes = "Billetes";
$Bolsa = "Bolsa";
$Boton = "Bot&oacute;n";
$Buscar = "Buscar";
$Buscar_Contacto = "Buscar Contacto";
$Busqueda = "Busqueda";
$Busquedas = "Busquedas";
$Buscador = "Buscador";

$Caducadas = "Caducadas";
$Caducidad = "Caducidad";
$Caja = "Caja";
$Cajas = "Cajas";
$Calculadora = "Calculadora";
$Calculo = "C&aacute;lculo";
$Calendario = "Calendario";
$Calendario_Economico = "Calendario Econ&oacute;mico";
$Calle = "Calle";
$Calles = "Calles";
$Cambiada = "Cambiada";
$Cambiar = "Cambiar";
$Cambio_Importe_a = "Cambio Importe a";
$Cambio = "Cambio";
$Cambios_fecha = "Cambio de fecha";
$Campos = "Campos";
$Campos_obligatorios = "Campos obligatorios";
$Cancelar = "Cancelar";
$Cantidad = "Cantidad";
$Caracteres = "Car&aacute;cteres";
$Caracteristica = "Caracter&iacute;stica";
$Caracteristicas = "Caracter&iacute;sticas";
$Cargo = "Cargo";
$carpeta = "carpeta";
$Carta = "Carta";
$Catalan = "Catal&aacute;n";
$Castellano = "Castellano";
$Cat = "Cat";
$Catalogo = "Catalogo";
$Catalogados = "Catalogados";
$Catalogar = "Catalogar";
$Categorias = "Categorias";
$Central = "Central";
$Certificacion = "Certificaci&oacute;n";
$Certificaciones = "Certificaciones";
$Cerrada = "Cerrada";
$Cerrar = "Cerrar";
$Cierre_ano_ant = "Cierre A&ntilde;o Pasado";
$Clase = "Clase";
$Clasificacion = "Clasificaci&oacuten";
$Clasificar = "Clasificar";
$CLIENTE = "CLIENTE";
$Cliente = "Cliente";
$Clientes =  "Clientes";
$Cliente_fidelizado = "Cliente fidelizado";
$Cliente_vip = "Cliente vip";
$Cobertura = "Cobertura";
$Cobrada = "Cobrada";
$Cobrado = "Cobrado";
$Cobro = "Cobro";
$Cobros = "Cobros";
$Codificado = "Codificado";
$Codigo = "C&oacute;digo";
$Color = "Color";
$Colores = "Colores";
$Coincidencias = "Coincidencias";
$Comentarios = "Comentarios";
$Comercial = "Comercial";
$Completa = "Completa";
$Completo = "Completo";
$Comunicacion = "Comunicaci&oacute;n";
$Comunidad_autonoma = "Comunidad Autonoma";
$Comunidades_autonomas = "Comunidades Autonomas";
$Conclusion = "Conclusi&oacute;n";
$Concepto = "Concepto";
$Con_delegaciones_asociadas = "Con delegaciones asociadas.";
$Conexion = "Conexi&oacute;n";
$Consumidas = "Consumidas";
$Condiciones = "Condiciones";
$Condiciones_pago = "Condiciones de pago";
$Configuracion = "Configuraci&oacute;n";
$Configurar = "Configurar";
$Confirmada = "Confirmada";
$Contacto = "Contacto";
$CONTACTOS = "CONTACTOS";
$Contactos = "Contactos";
$Control = "Control";
$Controles_de_calidad = "Controles de calidad";
$Contenidos = "Contenidos";
$Contenido = "Contenido";
$Contenido_Estendido = "Contenido Estendido";
$Contrasena = "Contrase&ntilde;a";
$Contrasenas = "Contrase&ntilde;as";
$Contrato = "Contrato";
$Contratos = "Contratos";
$Convertir = "Convertir";
$ConvertirAArticulo = "Convertir a Art&iacute;culo";
$Correcto = "Correcto";
$Correo = "Correo";
$Corriente = "Corriente";
$Costes = "Costes";
$Costes_Adicionales = "Costes Adicionales";
$CP = "CP";
$Creacion = "Creaci&oacute;n";
$Crear = "Crear";
$Cuenta = "Cuenta";
$Cuenta_Bancaria = "Cuenta Bancaria";
$Cuentas = "Cuentas";
$Cuenta_Contable = "Cuenta Contable";
$Curso = "Curso";
$Cursos = "Cursos";

$Dato = "Dato";
$Datos = "Datos";
$Datos_Adicionales = "Datos Adicionales"; 
$Datos_Administrativos = "Datos Administrativos";
$Datos_Bancarios = "Datos Bancarios";
$Datos_Comerciales = "Datos Comerciales";
$Datos_Contacto = "Datos Contacto";
$Datos_Facturacion = "Datos Facturaci&oacuten";
$Datos_Fiscales = "Datos Fiscales";
$Datos_fiscales_incompletos = "NIF/CIF/NIE incorrectos.";
$Datos_Generales = "Datos Generales";
$Datos_Tecnicos = "Datos T&eacute;cnicos";
$Definicion = "Definici&oacute;n";
$Definiciones = "Definiciones";
$Delegacion = "Delegaci&oacute;n";
$Departamento = "Departamento";
$Departamentos = "Departamentos";
$Dependencia = "Dependencia";
$Dependencias = "Dependencias";
$Desactivar = "Desactivar";
$Desaprobar = "Desaprobar";
$Desarrollo = "Desarrollo";
$Descatalogado = "Descatalogado";
$Descatalogados = "Descatalogados";
$Descatalogar = "Descatalogar";
$Descripcion = "Descripci&oacute;n";
$Descuento = "Descuento";
$Desde= "Desde";
$desde = "desde";
$Desde_archivo = "Desde archivo";
$Desglosar = "Desglosar";
$Desmarcar = "Desmarcar";
$Desplazamiento = "Desplazamiento";
$Desplazamientos = "Desplazamientos";
$Desplegar = "Desplegar";
$Despredeterminar = "Despredeterminar";
$Destino = "Destino";
$Destinatario = "Destinatario";
$Detalles = "Detalles";
$Dia = "D&iacute;a";
$diaas_naturales = "d&iacute;a/es naturales";
$Dias = "Dias";
$Dias_festivos = "Dias Festivos";
$Dias_libres_any = "Dias Libres/ A&ntilde;o";
$Dias_vacaciones_any = "Dias Vacaciones/ A&ntilde;o";
$Direcciones = "Direcciones";
$Direccion = "Direcci&oacute;n";
$Direcciones_Envio = "Direcciones de Envio";
$disponible = "disponible";
$Dispositivo = "Dispositivo";
$Dispositivos = "Dispositivos";
$Divisa = "Divisa";
$Divisas = "Divisas";
$Documentos = "Documentos";
$DOMICILIADA = "DOMICILIADA";
$Duplicado = "Duplicado";
$Duplicar = "Duplicar";
$Duracion = "Duraci&oacute;n";
$Efectivo = "Efectivo";
$Echo = "Echo";
$Edicion = "Edici&oacute;n";
$Editable = "Editable";
$Editar = "Editar";
$Ejecutar = "Ejecutar";
$Electronico = "Electr&oacute;nico";
$Elementos = "Elementos";
$EliminacionMasiva = "Eliminaci&oacute;n Masiva";
$Eliminada = "Eliminada";
$Eliminar = "Eliminar";
$Email = "E-mail";
$Empleado = "Empleado";
$Empleados = "Empleados";
$Empresa = "Empresa";
$en_orden_alfabetico = " en orden alfab&eacute;tico :";
$Entidad = "Entidad";
$Entrada = "Entrada";
$Entrar = "Entrar";
$Entrega = "Entrega";
$Enviar = "Enviar";
$Envio = "Envio";
$envio = "envio";
$Es = "Es";
$Escandallo = "Escandallo";
$escandallo = "escandallo";
$Escritura = "Escritura";
$Espacio = "Espacio";
$Especificos = "Espec&iacute;ficos";
$Esquema = "Esquema";
$Estado = "Estado";
$Estados = "Estados";
$Estanteria = "Estanteria";
$Estanterias = "Estanterias";
$Estado_de_la_Certificacion = "Estado de la Certificaci&oacute;n";
$Estado_del_Servicio = "Estado del Servicio";
$Estado_de_Cuentas = "Estado de Cuentas";
$Etiqueta = "Etiqueta";
$Etiquetas = "Etiquetas";
$Error = "Error";
$Experiencia = "Experiencia";
$Explotar = "Explotar";
$Exportar = "Exportar";
$Extendido = "Extendido";
$Externo = "Externo";
$Extranet = "Extranet";
$Extranjero = "Extranjero";

$Fabricante = "Fabricante";
$Factura = "Factura";
$Facturado = "Facturado";
$Facturar = "Facturar";
$Facturas = "Facturas";
$Facturacion = "Facturaci&oacute;n";
$FACTURADO = "FACTURADO";
$Familia = "Familia";
$Familias = "Familias";
$Fax = "Fax";
$Fecha = "Fecha";
$Fecha_Alta = "Fecha Alta";
$Fecha_Baja = "Fecha Baja";
$Fecha_Fin = "Fecha Fin";
$Fecha_Incorporacion = "Fecha Incorporaci&oacute;n";
$Fecha_Inicio = "Fecha Inicio";
$Fecha_Prevision = "Fecha Previsi&oacuten";
$Festividad = "Festividad";
$FICHA = "FICHA";
$Ficha = "Ficha";
$Ficha_de_Contacto = "Ficha de Contacto";
$Filtrado = "Filtrado";
$Filtrado_por = "Filtrado por";
$Filtrar = "Filtrar";
$Fin = "Fin";
$Final = "Final";
$finalizable = "finalizable : Contiene tareas no finalizadas";
$Finalizacion = "Finalizaci&oacute;n";
$Finalizada = "finalizada";
$Finalizar = "Finalizar";
$Firma = "Firma";
$Firmante = "Firmante";
$Fiscal = "Fiscal";
$Fisica = "F&iacute;sica";
$Forma = "Forma";
$Formacion = "Formaci&oacute;n";
$Formacion_general = "Formaci&oacute;n General";
$Formacion_especifica = "Formaci&oacute;n Espec&iacute;fica";
$Formato = "Formato";
$Formulario = "Formulario";
$Formulario_Subir_Archivo = "Formulario Subir Archivo";
$Forzado = "Forzado";
$Fuentes = "Fuentes";
$Fuera = "Fuera";
$Funcion = "Funci&oacute;n";
$Funciones = "Funciones";

$Gastos = "Gastos";
$General = "General";
$Generales = "Generales";
$Genericos = "Gen&eacutericos";
$Gestion = "Gesti&oacute;n";
$Gestion_Certificaciones = "Gesti&oacute;n de Certificaciones";
$Gestion_Comercial = "Gesti&oacute;n Comercial";
$Grafico = "Gr&aacute;fico";
$Grupo = "Grupo";
$Grupos = "Grupos";
$Guardadas = "Guardadas";
$Guardar = "Guardar";
$Guardar_Busqueda = "Guardar Busqueda";
$Guardias = "Guardias";

$Habilidades_personales= "Habilidades Personales";
$Hasta= "Hasta";
$hasta = "hasta";
$Herramienta = "Herramienta";
$Historial = "Historial";
$HISTORICO = "HIST&Oacute;RICO";
$Historico = "Hist&oacute;rico";
$Hoja = "Hoja";
$Hojas = "Hojas";
$Hora = "Hora";
$Hora_Inicio = "Hora Inicio";
$Hora_Fin = "Hora Fin";
$Horario = "Horario";
$Horario_atencion = "Horario Atenci&oacute;n";
$Horarios = "Horarios";
$Horas = "Horas";

$Identificarse = "Identificarse";
$Idioma = "Idioma";
$Idiomas = "Idiomas";
$Imagen = "Imagen";
$Imagenes = "Imagenes";
$Impartido_por = "Impartido por";
$Importar = "Importar";
$Importe = "Importe";
$Impresion = "Impresi&oacute;n";
$Impresos = "Impresos";
$IMPRIMIR = "IMPRIMIR";
$Imprimir = "Imprimir";
$Imprimir_Lista = "Imprimir Lista";
$Inactivo = "Inactivo";
$Incidencia = "Incidencia";
$Incidencias = "Incidencias";
$incluido = "incluido";
$Incompatibles = "Incompatibles";
$Incremento = "Incremento";
$Indicador = "Indicador";
$Indicadores = "Indicadores";
$info = "info";
$Informacion = "Informaci&oacute;n";
$Informes = "Informes";
$Ingresos = "Ingresos";
$Inicial = "Inicial";
$Inicio = "Inicio";
$Insertada = "Insertada";
$Insertar = "Insertar";
$Interno = "Interno";
$Introduccion = "Introducci&oacute;n";
$Inventario = "Inventario";
$Invitadas = "Invitadas";

$Jornada = "Jornada";
$Jornada_anual = "Jornada Anual";
$Juridica = "Jur&iacute;dica";

$Laborables = "Laborables";
$Laboral = "Laboral";
$Lectura = "Lectura";
$Letra = "Letra";
$Licencia = "Licencia";
$Licencias = "Licencias";
$Limite = "Limite";
$Linea = "Linea";
$Lista = "Lista";
$Listar = "Listar : ";
$Listado = "Listado";
$Liquidado = "Liquidado";
$Localizacion = "Localizaci&oacute;n";
$Logistica = "Log&iacute;stica";
$Logo = "Logo";
$Logos = "Logos";

$Mantenimiento = "Mantenimiento";
$Mantenimientos = "Mantenimientos";
$manual = "manual";
$Marca = "Marca";
$Marcar = "Marcar";
$Marcas = "Marcas";
$Maximo = "M&aacute;ximo";
$Medio = "Medio";
$Medios = "Medios";
$Mejoras = "Mejoras";
$Memoria = "Memoria";
$Mensaje = "Mensaje";
$Mensual = "Mensual";
$Mes = "Mes";
$Meses = "Meses";
$messes_naturales = "mes/es naturales";
$Minimo = "M&iacute;nimo";
$Minutos = "Minutos";
$Modificadores = "Modificadores";
$Modificar = "Modificar";
$Modulo = "M&oacute;dulo";
$Modulos = "M&oacute;dulos";
$Monedas = "Monedas";
$Mostrar = "Mostrar";
$Motivo = "Motivo";
$Movil = "M&oacute;vil";

$Nacimiento = "Nacimiento";
$Nacion = "Naci&oacute;n";
$NBD = "NBD";
$Necesidades = "Necesidades";
$NIF = "NIF";
$Nivel = "Nivel";
$No = "No";
$Nombre = "Nombre";
$Nombre_cliente = "Nombre cliente";
$Nominas = "N&oacute;minas";
$No_sobre = "No Sobre";
$Normal = "Normal";
$Nota = "Nota";
$Notas = "Notas";
$Notificacion = "Notificaci&oacute;n";
$Notificaciones = "Notificaciones";
$Notificar = "Notificar";
$NoVer = "No Ver";
$Nueva = "Nueva";
$Nuevo = "Nuevo";
$nuevo = "nuevo";
$Numero = "N&uacute;mero";
$Numero_serie = "N&uacute;mero Serie";
$Num_ins_segsoc = "N&uacute;mero Inscripci&oacute;n Seguridad Social";
$Num_afil_segsoc = "N&uacute;mero Afiliaci&oacute;n Seguridad Social";

$Obligatorio = "Obligatorio";
$Obligatorios = "Obligatorios";
$Observacions = "Observaciones";
$Oferta_Comercial = "Oferta Comercial";
$Oficina_contable = "Oficina Contable";
$Opcional = "Opcional";
$Opciones = "Opciones";
$Orden = "Orden";
$Organigrama = "Organigrama";
$Organo_gestor = "Organo Gestor";
$Origen = "Origen";
$Origenes = "Origenes";
$Original = "Original";
$OT = "OT";
$Otras = "Otras";
$Otro = "Otro";

$PAGADA = "PAGADA";
$Pago = "Pago";
$Pagos = "Pagos";
$Pais = "Pa&iacute;s";
$Paises = "Paises";
$Papel = "Papel";
$Panel_usuario = "Panel de Usuario";
$Para = "Para";
$Parada = "Parada";
$Parametros = "Parametros";
$Parcial = "Parcial";
$Pasillo = "Pasillo";
$Pausada = "Pausada";
$Pausadas = "Pausadas";
$Pausar = "Pausar";
$Pedido = "Pedido";
$PENDIENTE = "PENDIENTE";
$Pendiente = "Pendiente";
$Pendientes = "Pendientes";
$Periodo = "Periodo";
$Periodos = "Periodos";
$Permiso = "Permiso";
$Permisos = "Permisos";
$Personas = "Personas";
$Personal = "Personal";
$PERSONALES = "PERSONALES";
$Personales = "Personales";
$Personalizada = "Personalizada";
$Planificado = "Planificado";
$Plantilla = "Plantilla";
$Plantillas = "Plantillas";
$Plataforma = "Plataforma";
$Plegar = "Plegar";
$Poblacion = "Poblaci&oacute;n";
$Por = "Por";
$por = "por";
$Porcentage = "Porcentage";
$Por_clientes = "Por clientes";
$por_codigo = "por codigo";
$por_defecto = "por defecto";
$por_empresa = " por empresa";
$por_nombre = " por nombre";
$Posibles = "Posibles";
$Posicion = "Posici&oacute;n";
$Postal = "Postal";
$Precio = "Precio";
$Precios = "Precios";
$Predet = "Predet.";
$Predeterminar = "Predeterminar";
$Prefijo = "Prefijo";
$Presupuesto = "Presupuesto";
$Prevision = "Previsi&oacute;n";
$Primera = "Primera";
$Principal = "Principal";
$Privada = "Privada";
$Producto = "Producto";
$Propietario = "Propietario";
$proveedor = "proveedor";
$Proveedor = "Proveedor";
$Proveedores = "Proveedores";
$Provincia = "Provincia";
$provisional = "provisional";
$Proximas = "Pr&oacute;ximas";
$Proyecto = "Proyecto";
$Proyectos = "Proyectos";
$Puerto = "Puerto";
$Puesto = "Puesto";
$Puesto_trabajo = "Puesto de Trabajo";
$Puestos_trabajo = "Puestos de Trabajo";
$PVP = "PVP";
$PVD = "PVD";

$Reabierta = "Reabierta";
$Realizado = "Realizado";
$Recalcular = "Recalcular";
$Recibo = "Recibo";
$Recibos = "Recibos";
$Recuperar = "Recuperar";
$Red = "Red";
$Redes_Sociales = "Redes Sociales";
$Referencias = "Referencias";
$Region = "Regi&oacute;n";
$Registrada = "Registrada";
$Registrar_Documento = "Registrar Documento";
$Registro = "Registro";
$Relacion = "Relaci&oacute;n";
$Relacionar = "Relacionar";
$Relacionada = "Relacionada";
$Relacionado = "Relacionado";
$Relaciones = "Relaciones";
$Remitente = "Remitente";
$Remoto = "Remoto";
$Remunerado = "Remunerado";
$Renovar = "Renovar";
$Repercutido = "Repercutido";
$Repetir = "Repetir";
$Reports = "Reports";
$Residente = "Residente";
$Responsable = "Responsable";
$Responsable_cliente = "Responsable Cliente";
$Responsable_tecnico = "Responsable T&eacute;cnico";
$Respuesta = "Respuesta";
$Resultado = "Resultado";
$Resultado_de_la_busqueda = "Resultado de la busqueda: ";
$Resumen = "Resumen";
$Resumenes = "Resumenes";
$Retenciones = "Retenciones";
$RRHH = "RRHH";

$Salir = "Salir";
$Seccion = "Secci&oacute;n";
$Secciones = "Secciones";
$Secretario = "Secretario/a";
$Sector = "Sector";
$Sectores = "Sectores";
$Seguridad = "Seguridad";
$Seleccionado = "Seleccionado";
$Seleccionar = "Seleccionar";
$Semana = "Semana";
$Serie = "Serie";
$Servicio = "Servicio";
$Servicios = "Servicios";
$Servidor = "Servidor";
$Servidores = "Servidores";
$Si = "Si";
$Siglas = "Siglas";
$Simbolo = "Simbolo";
$Simple = "Simple";
$SIN = "SIN";
$Sin = "Sin";
$SinAsunto = "Sin Asunto";
$Sin_clasificar = "Sin Clasificar";
$SinCliente = "Sin Cliente";
$SinContrato = "Sin Contrato";
$Sincronizaciones = "Sincronizaciones";
$Sincronizar = "Sincronizar";
$Sin_dependencias = "Sin Dependencia";
$Sistema = "Sistema";
$Situacion = "Situaci&oacute;n";
$SLA = "SLA";
$Sobre = "Sobre";
$Socio_tecnologico = "Socio Tecnol&oacute;gico";
$Solo = "Solo";
$Solo_predeterminado = "Solo predeterminado";
$Solucionado = "Solucionado";
$Soportado = "Soportado";
$Soporte = "Soporte";
$Stock = "Stock";
$Subir = "Subir";
$Subfamilia = "Subfamilia";
$Subfamilias = "Subfamilias";
$Subtipo = "Subtipo";
$Subtipos = "Subtipos";
$Subtotal = "Subtotal";
$Sumar = "Sumar";
$Superior = "Superior";

$Tabla = "Tabla";
$Tamano = "Tama&ntilde;o";
$Tarea = "Tarea";
$Tareas = "Tareas";
$Tarifa = "Tarifa";
$Tarifas = "Tarifas";
$Tecnico = "T&eacute;cnico";
$Tecnicos = "T&eacute;cnicos";
$Telefonica = "Telef&oacute;nica";
$Telefono = "Tel&eacute;fono";
$Temario = "Temario";
$Texto_Contenidos = "Texto de los Contenidos";
$Texto = "Texto";
$Ticket = "Ticket";
$Tiempo = "Tiempo";
$Tipo = "Tipo";
$Tipos = "Tipos";
$Titulo = "T&iacute;tulo";
$Todas = "Todas";
$Todo = "Todo";
$Todos = "Todos";
$Total = "Total";
$Totales = "Totales";
$Traduccion = "Traducci&oacute;n";
$Trabajado = "Trabajado";
$Trabajador = "Trabajador";
$Trabajadores = "Trabajadores";
$Trabajo = "Trabajo";
$Traspasar = "Traspasar";
$Traspaso = "Traspaso";
$Trato = "Trato";
$Tratos = "Tratos";
$Trimestre = "Trimestre";

$Ubicacion = "Ubicaci&oacute;n";
$Ubicaciones = "Ubicaciones";
$Ultima = "&Uacute;ltima";
$Ultimo = "&Uacute;ltimo";
$Ultimos = "&Uacute;ltimos";
$Unidad = "Unidad";
$Unidades = "Unidades";
$UnidadesATraspasar = "Unidades a traspasar";
$Unidad_tramitadora = "Unidad Tramitadora";
$Uso = "Uso";
$Usuario = "Usuario";
$Usuarios = "Usuarios";

$Vacaciones = "Vacaciones";
$Validado = "Validado";
$Valor = "Valor";
$Valoracion = "Valoraci&oacute;n";
$Valoraciones = "Valoraciones";
$Valores = "Valores";
$Vencimiento = "Vencimiento";
$Ver = "Ver";
$VerMas = "Ver Mas";
$Ver_Empleados = "Ver Empleados";
$Ver_Departamentos = "Ver Departamentos";
$Ver_Detalles = "Ver Detalles";
$Ver_Horas = "Ver Horas";
$Ver_Todos = "Ver Todos";
$Ver_Todos_Personales = "Ver Todos Personales";
$Ver_Por_Tipo = "Ver Por Tipo";
$Ver_Por_Usuario = "Ver Por Usuario";
$Version = "Versi&oacute;n";
$Versionar = "Versionar";
$Versiones = "Versiones";
$Versiones_actuales = "Versiones Actuales";
$Versiones_anteriores = "Versiones Anteriores";
$Vigente = "Vigente";
$Visible = "Visible";
$Visualizar = "Visualizar";
$Volver = "Volver";

$Web = "Web";

$ygriega = "y";

$Zona = "Zona";

$meses = array("Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre");
$dias = array("Lunes","Martes","Mi&eacute;rcoles","Jueves","Viernes","Sabado","Domingo");
$Lunes = "Lunes";
$Viernes = "Viernes";
$Enero = "Enero";
$Febrero = "Febrero";
$Marzo = "Marzo";
$Abril = "Abril";
$Mayo = "Mayo";
$Junio = "Junio";
$Julio = "Julio";
$Agosto = "Agosto";
$Septiembre = "Septiembre";
$Octubre = "Octubre";
$Noviembre = "Noviembre";
$Diciembre = "Diciembre";

#Mensajes
#Articulos
$ValorDefectoCaracteristicaArt = "Si existe un valor por defecto se ignorar&aacute; la tabla de opciones de dicha caracter&iacute;stica.";
$ErrorEscandallo = "No es posible incluir un articulo en s&iacute; mismo.";
$ErrorAnadirArticulo = "No es posible a&ntilde;adir el articulo. El codigo o el nombre del articulo ya existen.";
$duplicarArticulo = "Se duplicar&aacute; el articulo y todos los datos relacionados con este (almacenaje, stock, precios, etc.).";
$eliminarArticulo = "Se eliminar&aacute; el articulo en todo el progama. Todos los datos relacionados con &eacute;l ser&aacute;n inaccesible.";
$descatalogarArticulo = "El articulo estar&aacute; descatalogado, pero ser&aacute; accesible tanto a &eacute;l como a los datos relacionados.";
$catalogarArticulo = "El articulo volver&aacute; al cat&aacute;logo habitual de articulos con todas sus funciones y datos relacionados.";
#Auxiliares
$ayuda_iso_idioma = "El idioma tiene que cumplir la norma ISO 639-1:2002 Alpha-2.<br>Consultar ";
$ayuda_iso_pais = "Las siglas tienen que cumplir la norma ISO 3166-1:2006 Alpha-3.<br>Consultar ";
$errorEliminarGrupo = "No se puede eliminar un grupo que tenga m&oacute;dulos asociados.";
#Clientes
$OkActualizacionCliente = "El tipo de los clientes se ha actualizado con &eacute;xito";
$ErrorActualizacionCliente = "El tipo de los clientes no se ha actualizado correctamente";
$info_cliente_alias = "El Alias es el nombre que tendra la carpeta en el cloud donde el cliente podra consultar toda su documentaci&oacute;n desde el Area de Clientes";
$info_cliente_vip = "El Cliente VIP es aquel cliente con consideraciones especiales: Importancia estrat&eacute;gica para la empresa";
#Contraseñas
$CambioPassCorrecto = "La contrase&ntilde;a se ha modificado correctamente";
$Redireccion10seg = "En 10 segundos ser&aacute; redirigido por motivos de seguridad.";
$ContrasenyaAppErrorEliminar = "No se puede eliminar esta aplicaci&oacute;n, ya que existen contrase&ntilde;as asociadas.";
$ContrasenyaSinContrato = "No se puede introducir una contrase&ntilde;a sin indicar el contrato.";
#Contratos
$ContratoErrorEliminar = "No se puede eliminar este contrato, ya que existen incidencias asociadas.";
$ContratoPlantillaErrorEliminar = "No se puede eliminar esta plantilla de contrato, ya que existen contratos asociados.";
$ContratoTipoErrorEliminar = "No se puede eliminar este tipo de contrato, ya que existen contratos asociados.";
$ErrorServicio = "Un servicio con el mismo nombre ya existe en este contrato";
$Explicacion_cobertura = "El periodo de cobertura de un servicio es la disponibilidad para la recepci&oacute;n de incidencias. Siendo el primer valor las horas al dia y el segundo los dias a la semana. Ejemplo : 8x5 equivale a 8 horas al dia 5 dias a la semana.";
$Explicacion_respuesta = "El tiempo de respuesta de una incidencia empieza a contar una vez recepcionada. Si es NBD, una vez fuera del horario laboral, la incidencia pasa al siguiente dia laboral.";
$info_contrato_notificaciones = "Gesti&oacute;n de las notificaciones de los servicios. Se enviar&aacute;n notificaciones al usuario escogido cuando la incidencia tenga el servicio y el usuario de origen escogido, y cuando se realize una de las acciones escogidas sobre ella.";
$info_contrato_archivos = "El archivo a subir es el contrato escaneado una vez firmado por ambas partes";
$info_contrato_tecnicos = "Gesti&oacute; de los t&eacute;cnicos asignados a este contrato";
$info_contrato_servicios1 = "Si para aquellos servicios que van incluidos en el contrato y no son seleccionables por el cliente.";
$info_contrato_servicios2 = "Si el servicio es visible para el cliente en la extranet, secci&oacute;n contratos.";
$info_contrato_servicios3 = "Si el cliente puede abrir incidencias sobre este servicio.";
$info_contrato_servicios4 = "Si el cliente puede ver la duraci&oacute;n de las incidencias.";
$info_contrato_servicios5 = "Horas de cobertura del servicio.";
$info_contrato_servicios6 = "Tiempo m&aacute;ximo de resoluci&oacute;n de incidencias del servicio en SLA.";
$info_contrato_servicios7 = "(Next Bussines Day) Si las incidencias hay que resolverlas dentro del horario laboral.";
$info_contrato_servicios8 = "Porcentage m&iacute;nimo de incidencias que se deben resolver en el tiempo y la cobertura asociados.";
$info_contrato_servicios9 = "Identificador &uacute;nico del servicio en el sistema.";
$info_contrato_servicios10 = "Envio autom&aacute;tico de email en el modulo de incidencias.";
$info_contrato_servicios11 = "Nombre de la funci&oacute;n a ejecutar para gestionar las incidencias abiertas de los email recibidos en Soporte.";
$info_contrato_servicios12 = "Codigo de quien abre incidencias relacionadas con este servicio.";
$info_contrato_servicios13 = "Contabilidad de las horas si se trata de un contrato de bolsa de horas.";
#Facturacion
$info_facturacion_orden = "Orden - Orden en que aparecen los difrentes tipos en el listado superior.";
$info_facturacion_plantilla = "Plantilla - Hace referencia a si este tipo debe de poder facturarse de forma continua.";
$info_facturacion_plantilla_dias = "D&iacute;as - La periocidad en d&iacute;as en que debe regenerarse una nueva plantilla.";
$info_facturacion_ver_prevision = "V.Prev - (Visualizar previsi&oacute;n) Visualiza en el listado la fecha de previsi&oacute;n (usado para pedidos de clientes/proveedores).";
$info_facturacion_ver_prevision_dias = "D&iacute;as - D&iacute;as que suma de forma autom&aacute;tica a la previsi&oacute;n. Fecha de previsi&oacute;n = Fecha actual + D&iacute;as.";
$info_facturacion_ver_vencimiento = "V.Ven - (Visualizar Vencimiento) Visualiza en el listado el vencimiento de la factura. Fecha de vencimiento = Fecha actual + D&iacute;as de la ficha cliente.";
$info_facturacion_ver_referencia_cliente = "V.Ref - (Visualizar Referencia del Cliente) Visualiza en el listado n&uacute;mero de referencia del cliente y nombre del solicitante.";
$info_facturacion_ver_subtipo = "V.Sub - (Visualizar Subtipos) Visualiza el subtipo (en caso de que existan).";
$info_facturacion_ver_recibos = "V.Rec - (Visualizar Recibos) Permite la gesti&oacute;n de recibos para el control del cobro.";
$info_facturacion_presupuesto = "Presu - Formato de presupuesto. Vencimiento y c&aacute;lculo de costes.";
$info_facturacion_presupuesto_dias = "D&iacute;as - D&iacute;as que suma a la caducidad del presupuesto. Fecha de caducidad = Fecha actual + D&iacute;as.";
$info_facturacion_stock = "Stock - Indica c&oacute;mo este tipo influye en el stock.";
$info_facturacion_aprobar = "Aprobar - Dar aprovaci&oacute;n a un presupuesto.";
$info_facturacion_ver_rfq = "V.RFQ - (Visualitzar RFQ) Visualita n&uacute;mero RFQ.";
$info_facturacion_caja = "Caja - Indica c&oacute;mo este tipo influye en la caja.";
$ayudaFacturaRelaciones = "Las relaciones entre tipos marcaran de donde a donde se pueden traspasar datos de facturaci&oacute;n.";
$ayudaFacturaEliminar = "Se eliminar&aacute; el articulo en todo el progama. Todos los datos relacionados con &eacute;l ser&aacute;n inaccesible.";
$ayudaFacturaCerrar = "Se cerrar&aacute; el documento y dejar&aacute; de ser visible, excepto en el hist&oacute;rico.";
$ayudaFacturaAbrir = "Se abrir&aacute; la factura y volver&aacute; a ser visible.";
$errorFacturaCrear = "Atenci&oacute;n : La fecha de la factura es superior a la fecha actual.";
$ayudaFacturaAprobar = "Se aprobar&aacute; el documento y se podr&aacute; facturar.";
$ayudaFacturaDesaprobar = "Se desaprobar&aacute; el documento y no se podr&aacute; facturar.";
$ayudaCuerpoConvertir = "Convierte la linea del documento en un nuevo art&iacute;culo. Se traspasar&aacute; tambi&eacute;n el calculo de coste, si lo hay.";
$ayudaCuerpoEliminar = "Se eliminar&aacute; la linea en todo el progama. Todos los datos relacionados con ella ser&aacute;n inaccesible.";
$pregunta_recalculo = "&iquest;Seguro que desea hacer un rec&aacute;lculo total? Esta acci&oacute;n puede durar varios minutos, ya que se har&aacute; un rec&aacute;lculo total desde el 1 de Enero de 2012.";
$InfoCambioFormaPagoTPV = "Forma de pago cambiada correctamente.";
$InfoCambioFormaPagoTPV2 = "Ha realizado otro cambio en la forma de pago.";
#General
$UsuarioNoAutorizado = "USUARIO NO AUTORIZADO";
$error_incidencia_busqueda = "Para buscar por fechas, es necesario mes y a&ntilde;o.";
$errorSubirArchivoDuplicado = "No se puede a&ntilde;adir el archivo por que ya existe uno con el mismo nombre.";
$errorSubirArchivoTamany = "No ha podido transferirse el archivo.<br>No puede exceder el tama&ntilde;o indicado";
$errorSubirArchivo = "No ha podido transferirse el archivo.";
$pregunta_eliminar = "&iquest;Desea eliminar el elemento seleccionado?";
$mesaje_modificar = "Se ha modificado correctamente";
#Incidencias
$ErrorRelacion = "El valor introducido no es num&eacute;rico o no pertenece a un ID de una incidencia existente";
$ErrorSinTextoDuracion = "No se puede introducir una incidencia sin texto y/o duraci&oacute;n";
$ErrorSinServicioCliente = "No se puede introducir una incidencia sin servicio SIM o cliente";
$ErrorSinAsunto = "No se puede introducir una incidencia sin asunto";
$ErrorFinalizacion = "No se puede finalizar una incidencia sin notas de conclusi&oacute;n, sin servicio o pausada";
$ErrorBusqueda = "Para buscar por fechas, es necesario mes y a&ntilde;o.";
$ayudaIncidenciaCliente = "Acceso al formulario de inserci&oacute;n de contacto";
$ayudaIncidenciaContrasena = "Acceso a las contrase&ntilde;as del cliente";
$ayudaIncidenciaContrato = "Acceso a los contratos del cliente";
$ayudaRelacionar = "&iquest;Seguro que desea relacionar esta incidencias?";
$ayudaRelacionar2 = "La incidencia ";
$ayudaRelacionar3 = " se convertir&aacute en una nota de la incidencia ";
#Login
$ayudaLogin = "&iquest;Olvidaste el usuario y/o la contrase&ntilde;a?";
$asuntoMensajeRecuperacion = "Mensaje de recuperaci&oacute;n de contrase&ntilde;a.";
$textoMensajeRecuperacion1 = "Siga el link para restaurar la contrase&ntilde;a";
$textoMensajeRecuperacion2 = "No responda este e-mail";
$ayudaMensajeRecuperacion = "Se ha enviado un e-mail para la recuperaci&oacute;n del usuario y la contrase&ntilde;a a : ";
$errorMensajeRecuperacion = "Esta direcci&oacute;n e-mail no esta registrada";
#Panel Usuario
$ayudaPanelUserPass = "M&aacute;x. 10 car&aacute;cteres";
$ayudaPanelUserPass2 = "Si no pudiera hacer correctamente el login de nuevo, borre las cookies referentes a solucions-im.com de su navegador.";
$errorPanelUserPass = "Error al introducir las contrase&ntilde;as.";
#RRHH
$ErrorEmpleadoHorario = "Las fechas o las horas introducidas no son correctas";
$ErrorEmpleadoCalendario = "Las fechas no son correctas";
$ErrorPuestoDasactivar = "No se puede desactivar un puesto de trabajo con un empleado asignado";
#Usuarios
$UseNoAutorizado = "<br><center><table><tr><td>Usuario no autorizado.</td></tr></table></center>";
$UsuarioYaReg = "<br>Nombre de usuario ya registrado.";
$NombreIncorrecto = "<br>Valor en el campo nombre de usuario incorrecto.";
$MailYaReg = "<br>Direcci&oacute;n e-mail ya registrada.";
$MailIncorrecto = "<br>Valor en el campo e-mail incorrecto.";
$PassIncorrecto = "<br>Valor en los campos passwords incorrecto.";
$CompletaCorrect = "Completa correctamente todos los campos obligatorios.";
$InvalidarUsuario = "<br><br>&iquest;Seguro que desea invalidar este usuario?";
$ErrorPass = "<br><br>Error al introducir las contrase&ntilde;as<br><br>";
$NotasDes = "No se puede introducir una incidencia sin texto";
$cambiarDatos = "Si desea cambiar los datos de la empresa, pongase en contacto con ";
#Comercial
$pregunta_versionar = "&iquest;Desea versionar el elemento seleccionado?";
$infoServidores = "Nombre descriptivo de cada servidor necesario en el cliente";
$infoDesglosar = "Se muestran o no todos los articulos de la oferta en la impresi&oacute; en PDF. Si es no, solo se muestra el primer articulo de la oferta con el precio total de todos los articulos.";
#Texto Ajuda
$FacturasAyudaColores = "
	<p>En el listado general, las factura se muestran en diferentes colores para diferenciarlas seg&uacute;n diferentes motivos.</p>
	<ul>
		<li>&bull; Rojo: si no esta pagada y ha pasado la fecha de vencimiento.</li>
		<li>&bull; Naranja: si no esta pagada y faltan menos de 30 dias para la fecha de vencimiento.</li>
		<li>&bull; Blanco: si no esta pagada y faltan m&aacute;s de 30 dias para la fecha de vencimiento o esta cerrada.</li>
		<li>&bull; Verde: si esta pagada.</li>
	</ul>
";

$IncidenciasAyudaColores = "
	<p>Los botones sobre els listado hacen referencia a cada uno de los clientes que tienen incidencias abiertas. En cada bot&oacute;n aparece el \"alias\" del cliente y la cantidad de incidencias de cada tipo que tiene abiertas.</p>
	<ul>
		<li>&bull; Naranja: numero de incidencias con menos de 4 horas para quedar fuera de SLA.</li>
		<li>&bull; Rojo: numero de incidencias fuera de SLA.</li>
		<li>&bull; Gris: numero de incidencias pausadas.</li>
		<li>&bull; Amarillo: numero de incidencias con nueva nota de desarrollo del cliente.</li>
	</ul>
	<p>En el listado general, las incidencias se muestran en diferentes colores para diferenciarlas seg&uacute;n diferentes motivos.</p>
	<ul>
		<li>&bull; Negro: si la incidencia no tiene el campo “(Contrato) Servicio” informado.</li>
		<li>&bull; Gris: si la incidencia esta pausada.</li>
		<li>&bull; Rojo: si la incidencia esta fuera de SLA.</li>
		<li>&bull; Naranja: si la incidencia tiene menos de 4 horas para quedar fuera de SLA.</li>
		<li>&bull; Blanco: si no tiene SLA o tiene m&aacute;s de 4 horas para quedar fuera de SLA.</li>
	</ul>
";

$IncidenciasAyudaNotificaciones = "
	<p>Para poder realizar las notificaciones es necesario tener el campo “usuario de origen” informado en la incidencia. Las notificaciones solo se realizar&aacute;n a usuarios que no sean de Solucions-IM.</p>
	<p>Cada vez que realicemos una acci&oacute;n referente a las incidencias se generara una notificaci&oacute;n hacia el cliente de la incidencia en los siguientes casos:</p>
	<ul>
		<li>&bull; Al insertar una incidencia nueva.
			<p>Cuando un cliente env&iacute;a un correo a la direcci&oacute;n soporte@solucions-im.com, se genera una incidencia nueva y se env&iacute;a un correo de respuesta al cliente inform&aacute;ndole.</p>
			<p>Si creamos una incidencia desde SIMges e indicamos el usuario de origen, tambi&eacute;n se enviar&aacute; una notificaci&oacute;n a dicho usuario.</p>
		</li>
		<li>&bull; Al editar una incidencia.
		<p>Solo se env&iacute;a una notificaci&oacute;n al cliente cuando:</p>
		<ul>
			<li>&bull; Si se ha modificado el usuario de destino.</li>
			<li>&bull; Si se han modificado las notas de registro.</li>
			<li>&bull; Si se añade una nota de desarrollo nueva y el campo “visible cliente” es “si”.</li>
			<li>&bull; Si se modifica una nota de desarrollo existente (solo el texto) si el campo “visible cliente” es “si”.</li>
			<li>&bull; Si se finaliza la incidencia.</li>
			<li>&bull; Si se reabre una incidencia.</li>
			<li>&bull; Si se relaciona la incidencia con otra.</li>
		</ul>
		</li>
		<li>&bull; Al eliminar la incidencia.
	</ul>
";

?>