<?php
if ($option == 300) {
	if ($soption == 0) {
		echo "<br><center><strong>POLITICA DE PRIVACIDAD</strong></center><br>";
		echo "Mediante este aviso, Solucions Globals Maresme S.L., sociedad con domicilio en Palafolls, Montserrat 19 y CIF B-62.203.211 (en adelante, multivia.com) informa a los usuarios de los distintos portales de Internet de su propiedad (en adelante, los \"Usuarios\" y el \"Portal\") acerca de su política de protección de datos de carácter personal (en adelante, \"los Datos Personales\") para que los Usuarios determinen, libre y voluntariamente, si desean facilitar a multivia.com los Datos Personales que se les puedan requerir o que se puedan obtener de los Usuarios con ocasión de la suscripción o alta en algunos de los servicios ofrecidos por multivia.com en el Portal o a través del Portal. multivia.com se reserva el derecho a modificar la presente política para adaptarla a novedades legislativas o jurisprudenciales así como a prácticas de la industria. En dichos supuestos, multivia.com anunciará en esta página los cambios introducidos con razonable antelación a su puesta en práctica.";
		echo "<br><br>";
		echo "Ciertos servicios prestados en el Portal pueden contener condiciones particulares con previsiones específicas en materia de protección de Datos Personales.";
		echo "<br><br>";
		echo "La recogida y tratamiento automatizado de los Datos Personales tiene como finalidad el mantenimiento de la relación contractual en su caso establecida con Multivia.com, la gestión, administración, prestación, ampliación y mejora de los servicios en los que el Usuario decida suscribirse, darse de alta, o utilizar la adecuación de dichos servicios a las preferencias y gustos de los Usuarios, el estudio de la utilización de los servicios por parte de los Usuarios, el diseño de nuevos servicios relacionados con dichos servicios, el envío de actualizaciones de los servicios, el envío, por medios tradicionales y electrónicos, de información técnica, operativa y comercial acerca de productos y servicios ofrecidos por Multivia.com y/o por terceros, actualmente y en el futuro. La finalidad de la recogida y tratamiento automatizado de los Datos Personales incluye igualmente el envío de formularios de encuestas, que el Usuario no queda obligado a contestar.";
		echo "<br><br>";
		echo "Multivia.com ha adoptado los niveles de seguridad de protección de los Datos Personales legalmente requeridos, y procura instalar aquellos otros medios y medidas técnicas adicionales a su alcance para evitar la pérdida, mal uso, alteración, acceso no autorizado y robo de los Datos Personales facilitados a multivia.com. En particular, multivia.com utiliza sistemas de seguridad SSL (Secure Socket Layer) que, a través de sistemas de certificados y cifrado, permiten comprobar la autenticidad del Portal multivia.com desde donde se recaban sus Datos Personales, así como la integridad y confidencialidad de sus Datos Personales durante su transmisión (Ud. puede comprobar la implementación del SSL al registrarse dado que la página de registro comienza con \"htpps\", en lugar del \"http\", y le aparecerá un pequeño candado cerrado en la parte inferior de su navegador). Ello no obstante, el Usuario debe ser consciente de que las medidas de seguridad en Internet no son inexpugnables.";
		echo "<br><br>";
		echo "Multivia.com puede utilizar cookies cuando un Usuario navega por los sitios y páginas web del Portal. Las cookies que se puedan utilizar en los sitios y páginas web del Portal se asocian únicamente con el navegador de un ordenador determinado (un Usuario anónimo), y no proporcionan por sí el nombre y apellidos del Usuario. Gracias a las cookies, resulta posible que Multivia.com reconozca los navegadores de los Usuarios registrados después de que éstos se hayan registrado por primera vez, sin que tengan que registrarse en cada visita para acceder a las áreas y servicios reservados exclusivamente a ellos. Las cookies utilizadas no pueden leer los archivos cookie creados por otros proveedores. El Usuario tiene la posibilidad de configurar su navegador para ser avisado en pantalla de la recepción de cookies y para impedir la instalación de cookies en su disco duro. Por favor, consulte las instrucciones y manuales de su navegador para ampliar ésta información. Para utilizar el Portal, no resulta necesario que el Usuario permita la instalación de las cookies enviadas por Multivia.com, sin perjuicio de que, en tal caso, será necesario que el Usuario se registre como usuario de cada uno de los servicios cuya prestación requiera el previo registro. Las cookies que se utilizan en los sitios y páginas web del Portal pueden ser servidas por Multivia.com, en cuyo caso se sirven desde los distintos servidores operados por éstas, o desde los servidores de determinados terceros que prestan a Multivia.com servicios y sirven las cookies por cuenta de Multivia.com (como por ejemplo, las cookies que se emplean para servir la publicidad o determinados contenidos y que hacen que el Usuario visualice la publicidad o ciertos contenidos en el tiempo, número de veces y forma predeterminados). Siempre que no haya activado la opción que impide la instalación de cookies en su disco duro, Ud. puede explorar su disco duro siguiendo el manual de instrucciones y ayuda de su sistema operativo (normalmente, en sistemas operativos Windows deberá consultar la carpeta \"C(o la unidad de disco correspondiente)/Windows/Cookies\") para conocer con mayor detalle cada servidor desde donde se envían las cookies.";
	}
}
?>