<?php
echo "<center><h2>IV ".$Jornada_monitorizacion."</h2></center><br>";
echo "<table class=\"prog\">";
	echo "<caption class=\"prog\">".$Programa ."</caption>";
	echo "<tr>";
		echo "<td class=\"prog\">09:45</td>";
		echo "<td class=\"prog2\">".$Benvinguda."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td class=\"prog\">09:50</td>";
		echo "<td class=\"prog2\">".$titol_ponencia_1."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td></td><td class=\"prog3\">".$decripcio_ponencia_1."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td class=\"prog\">10:10</td>";
		echo "<td class=\"prog2\">".$titol_ponencia_2."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td></td><td class=\"prog3\">".$decripcio_ponencia_2."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td class=\"prog\">10:35</td>";
		echo "<td class=\"prog2\">".$titol_ponencia_3."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td></td><td class=\"prog3\">".$decripcio_ponencia_3."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td class=\"prog\">11:00</td>";
		echo "<td class=\"prog2\">".$Cafe."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td class=\"prog\">11:30</td>";
		echo "<td class=\"prog2\">".$titol_ponencia_4."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td></td><td class=\"prog3\">".$decripcio_ponencia_4."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td class=\"prog\">12:00</td>";
		echo "<td class=\"prog2\">".$titol_ponencia_5."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td></td><td class=\"prog3\">".$decripcio_ponencia_5."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td class=\"prog\">12:30</td>";
		echo "<td class=\"prog2\">".$titol_ponencia_6."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td></td><td class=\"prog3\">".$decripcio_ponencia_6."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td class=\"prog\">13:30</td>";
		echo "<td class=\"prog2\">".$Cloenda." / ".$Dinar."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td class=\"prog\"></td>";
		echo "<td class=\"prog2\" style=\"color:black;\">";
			echo "<table>";
				echo "<tr>";
					echo "<td><img src=\"images/tecnocampusmataro-1.jpg\" height=\"250px\" width=\"450px\" alt=\"TCM\"></td>";
					echo "<td width=\"50px;\"></td>";
					echo "<td>".$Menu_Jornada."</td>";
				echo "</tr>";
			echo "</table>";
		echo "</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td class=\"prog\"></td>";
		echo "<td class=\"prog2\"></td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td class=\"prog\"></td>";
		echo "<td class=\"prog3\">".$Encuesta_satisfaccion."</td>";
	echo "</tr>";
echo "</table>";
echo "<br><br>";

?>
