<?php
echo "<center><h2>III ".$Jornada_monitorizacion."</h2></center><br>";
echo "<table class=\"prog\">";
	echo "<caption class=\"prog\">".$Programa ."</caption>";
	echo "<tr>";
		echo "<td class=\"prog\">09:45</td>";
		echo "<td class=\"prog2\">".$Benvinguda."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td class=\"prog\">10:10</td>";
		echo "<td class=\"prog2\">".$titol_ponencia_1."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td></td><td class=\"prog3\">".$decripcio_ponencia_1."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td class=\"prog\">10:30</td>";
		echo "<td class=\"prog2\">".$titol_ponencia_2."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td></td><td class=\"prog3\">".$decripcio_ponencia_2."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td class=\"prog\">11:10</td>";
		echo "<td class=\"prog2\">".$titol_ponencia_3."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td></td><td class=\"prog3\">".$decripcio_ponencia_3."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td class=\"prog\">11:30</td>";
		echo "<td class=\"prog2\">".$Cafe."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td class=\"prog\">12:00</td>";
		echo "<td class=\"prog2\">".$titol_ponencia_4."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td></td><td class=\"prog3\">".$decripcio_ponencia_4."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td class=\"prog\">13:00</td>";
		echo "<td class=\"prog2\">".$titol_ponencia_5."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td></td><td class=\"prog3\">".$decripcio_ponencia_5."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td class=\"prog\">13:30</td>";
		echo "<td class=\"prog2\">".$Cloenda."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td class=\"prog\">14:00</td>";
		echo "<td class=\"prog2\">".$Dinar."</td>";
	echo "</tr>";
echo "</table>";

?>
